import {ScoritoRace} from "./scorito-types";

export const races: ScoritoRace [] =
  [
    {
        "CompetitionId": 26,
        "EventId": 781,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_26.png",
        "MarketRoundId": 7133,
        "StageId": 2841,
        "Status": 0,
        "StartDate": "2026-02-28T11:00:00",
        "TranslatedDescription": "Cobbles",
        "TranslatedName": "Omloop Het Nieuwsblad",
        "TranslatedNameShort": "OML"
    },
    {
        "CompetitionId": 27,
        "EventId": 805,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_27.png",
        "MarketRoundId": 7134,
        "StageId": 2842,
        "Status": 0,
        "StartDate": "2026-03-01T11:20:00",
        "TranslatedDescription": "Sprinters",
        "TranslatedName": "Kuurne-Bruxelles-Kuurne",
        "TranslatedNameShort": "KBK"
    },
    {
        "CompetitionId": 41,
        "EventId": 811,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_41.png",
        "MarketRoundId": 7135,
        "StageId": 2843,
        "Status": 0,
        "StartDate": "2026-03-07T09:00:00",
        "TranslatedDescription": "Hills and gravel",
        "TranslatedName": "Strade Bianche",
        "TranslatedNameShort": "SB"
    },
    {
        "CompetitionId": 98,
        "EventId": 834,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_98.png",
        "MarketRoundId": 7136,
        "StageId": 2868,
        "Status": 0,
        "StartDate": "2026-03-14T10:00:00",
        "TranslatedDescription": "Mountains",
        "TranslatedName": "Paris - Nice",
        "TranslatedNameShort": "P-N"
    },
    {
        "CompetitionId": 99,
        "EventId": 841,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_99.png",
        "MarketRoundId": 7137,
        "StageId": 2869,
        "Status": 0,
        "StartDate": "2026-03-15T12:00:00",
        "TranslatedDescription": "Sprinters",
        "TranslatedName": "Tirreno - Adriatico",
        "TranslatedNameShort": "T-A"
    },
    {
        "CompetitionId": 28,
        "EventId": 812,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_28.png",
        "MarketRoundId": 7138,
        "StageId": 2844,
        "Status": 0,
        "StartDate": "2026-03-21T09:00:00",
        "TranslatedDescription": "Hills",
        "TranslatedName": "Milan-San Remo",
        "TranslatedNameShort": "MSR"
    },
    {
        "CompetitionId": 59,
        "EventId": 813,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_59.png",
        "MarketRoundId": 7139,
        "StageId": 2845,
        "Status": 0,
        "StartDate": "2026-03-25T09:00:00",
        "TranslatedDescription": "Sprinters",
        "TranslatedName": "Brugge-De Panne",
        "TranslatedNameShort": "BDP"
    },
    {
        "CompetitionId": 30,
        "EventId": 814,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_30.png",
        "MarketRoundId": 7140,
        "StageId": 2846,
        "Status": 0,
        "StartDate": "2026-03-27T09:00:00",
        "TranslatedDescription": "Cobbles",
        "TranslatedName": "E3 Saxo Bank Classic",
        "TranslatedNameShort": "E3"
    },
    {
        "CompetitionId": 33,
        "EventId": 815,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_33.png",
        "MarketRoundId": 7141,
        "StageId": 2847,
        "Status": 0,
        "StartDate": "2026-03-29T09:00:00",
        "TranslatedDescription": "Sprinters",
        "TranslatedName": "Gent-Wevelgem",
        "TranslatedNameShort": "GW"
    },
    {
        "CompetitionId": 29,
        "EventId": 816,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_29.png",
        "MarketRoundId": 7142,
        "StageId": 2848,
        "Status": 0,
        "StartDate": "2026-04-01T09:00:00",
        "TranslatedDescription": "Cobbles",
        "TranslatedName": "Dwars door Vlaanderen",
        "TranslatedNameShort": "DDV"
    },
    {
        "CompetitionId": 32,
        "EventId": 817,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_32.png",
        "MarketRoundId": 7143,
        "StageId": 2849,
        "Status": 0,
        "StartDate": "2026-04-05T09:00:00",
        "TranslatedDescription": "Hills and cobbles",
        "TranslatedName": "Tour of Flanders",
        "TranslatedNameShort": "TOF"
    },
    {
        "CompetitionId": 40,
        "EventId": 818,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_40.png",
        "MarketRoundId": 7144,
        "StageId": 2850,
        "Status": 0,
        "StartDate": "2026-04-08T09:00:00",
        "TranslatedDescription": "Sprinters",
        "TranslatedName": "Scheldeprijs",
        "TranslatedNameShort": "SP"
    },
    {
        "CompetitionId": 34,
        "EventId": 819,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_34.png",
        "MarketRoundId": 7145,
        "StageId": 2851,
        "Status": 0,
        "StartDate": "2026-04-12T09:00:00",
        "TranslatedDescription": "Cobbles",
        "TranslatedName": "Paris-Roubaix",
        "TranslatedNameShort": "PR"
    },
    {
        "CompetitionId": 31,
        "EventId": 820,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_31.png",
        "MarketRoundId": 7146,
        "StageId": 2852,
        "Status": 0,
        "StartDate": "2026-04-17T09:00:00",
        "TranslatedDescription": "Hills\n",
        "TranslatedName": "Flèche Brabançonne",
        "TranslatedNameShort": "BP"
    },
    {
        "CompetitionId": 37,
        "EventId": 821,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_37.png",
        "MarketRoundId": 7147,
        "StageId": 2853,
        "Status": 0,
        "StartDate": "2026-04-19T09:00:00",
        "TranslatedDescription": "Hills",
        "TranslatedName": "Amstel Gold Race",
        "TranslatedNameShort": "AGR"
    },
    {
        "CompetitionId": 35,
        "EventId": 822,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_35.png",
        "MarketRoundId": 7148,
        "StageId": 2854,
        "Status": 0,
        "StartDate": "2026-04-22T09:00:00",
        "TranslatedDescription": "Puncheurs",
        "TranslatedName": "Flèche Wallonne",
        "TranslatedNameShort": "LFW"
    },
    {
        "CompetitionId": 36,
        "EventId": 823,
        "ImageUrl": "https://cdn.scorito-sports.com/cycling/competition/country/competition_36.png",
        "MarketRoundId": 7149,
        "StageId": 2855,
        "Status": 0,
        "StartDate": "2026-04-26T09:00:00",
        "TranslatedDescription": "Hills",
        "TranslatedName": "Liège-Bastogne-Liège",
        "TranslatedNameShort": "LBL"
    }
]
